# Generated by Django 3.2 on 2021-04-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newref', '0002_touralter'),
    ]

    operations = [
        migrations.AddField(
            model_name='ref',
            name='bulletin_text',
            field=models.CharField(default='Ne partagez ce bulletin avec personne, car la personne pourrait voter à votre place.', max_length=1000),
        ),
        migrations.AddField(
            model_name='ref',
            name='depouillement',
            field=models.CharField(choices=[('ALT', 'Vote alternatif')], default='ALT', max_length=10),
        ),
        migrations.AddField(
            model_name='ref',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ref',
            name='secret_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ref',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ref',
            name='text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
