# Generated by Django 3.2 on 2021-04-30 15:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newref', '0003_auto_20210430_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='ref',
            name='hash',
            field=models.CharField(default='aze', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ref',
            name='bulletin_text',
            field=models.CharField(blank=True, default='Ne partagez ce bulletin avec personne, car la personne pourrait voter à votre place.', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ref',
            name='secret_key',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ref',
            name='text',
            field=models.CharField(default=datetime.datetime(2021, 4, 30, 15, 57, 12, 359474, tzinfo=utc), max_length=1000),
            preserve_default=False,
        ),
    ]
