# Generated by Django 3.2 on 2021-04-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newref', '0004_auto_20210430_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ref',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ref',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
