# Generated by Django 3.2 on 2021-05-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newref', '0005_auto_20210430_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='ref',
            name='bulletin_img',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='ref',
            name='depouillement',
            field=models.CharField(choices=[('ALT', 'Hiérarchisation des options & Vote alternatif'), ('CLASSIC', "Choix d'une option & Vote à un tour")], default='ALT', max_length=10),
        ),
    ]
