# Generated by Django 3.2 on 2021-05-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newref', '0007_auto_20210501_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='ref',
            name='status',
            field=models.CharField(choices=[('CONFIG', 'En cours de configuration'), ('RUN', 'Bulletins envoyés - En cours de vote'), ('FINISHED', 'Les résultats sont disponibles')], default='CONFIG', max_length=10),
        ),
    ]
