# Generated by Django 3.2 on 2021-05-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newref', '0008_ref_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawvote',
            name='status',
            field=models.CharField(choices=[('INIT', 'Statut initial'), ('SENT', 'Bulletin envoyé'), ('STUCK', 'Vote arrêté')], default='INIT', max_length=10),
        ),
    ]
