# Generated by Django 3.2 on 2021-05-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newref', '0009_rawvote_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ref',
            name='email_host',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='ref',
            name='email_host_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ref',
            name='email_host_user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ref',
            name='email_port',
            field=models.IntegerField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='ref',
            name='email_use_tls',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ref',
            name='depouillement',
            field=models.CharField(choices=[('ALT', 'Hiérarchisation des options & Vote alternatif')], default='ALT', max_length=10),
        ),
    ]
