# Generated by Django 3.2 on 2021-05-05 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newref', '0010_auto_20210504_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ref',
            name='depouillement',
            field=models.CharField(choices=[('ALT', 'Choix : Hiérarchisation des options (par Drag & Drop) - Comptabilisation : vote alternatif'), ('CLASSIC', "Choix : Sélection d'une option - Comptabilisation : Classique")], default='ALT', max_length=10),
        ),
        migrations.AlterField(
            model_name='touralter',
            name='num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='touralter',
            name='removed_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newref.option'),
        ),
    ]
