# Generated by Django 3.2 on 2021-05-07 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newref', '0011_auto_20210505_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ref',
            name='bulletin_img',
            field=models.CharField(default='https://www.batiactu.com/images/auto/620-465-c/20200311_170654_39186406illustration-wissanu99.jpg', max_length=300),
        ),
        migrations.AlterField(
            model_name='ref',
            name='bulletin_objet',
            field=models.CharField(default='Votre bulletin de vote', max_length=300),
        ),
        migrations.AlterField(
            model_name='ref',
            name='bulletin_text',
            field=models.CharField(default='Vous êtes invité.e à voter. Attention à ne pas partager ce bulletin : les personnes qui y accéderont pourront voter à votre place.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='ref',
            name='end',
            field=models.DateField(default=datetime.date(2021, 5, 14)),
        ),
        migrations.AlterField(
            model_name='ref',
            name='start',
            field=models.DateField(default=datetime.date(2021, 5, 7)),
        ),
    ]
