# Generated by Django 3.2 on 2021-05-21 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newref', '0016_auto_20210518_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawvote',
            name='crypted_json',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='ref',
            name='crypted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ref',
            name='email_host_cryped_password',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='ref',
            name='public_key',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='ref',
            name='end',
            field=models.DateField(blank=True, default=datetime.date(2021, 5, 28), null=True),
        ),
        migrations.AlterField(
            model_name='ref',
            name='start',
            field=models.DateField(blank=True, default=datetime.date(2021, 5, 21), null=True),
        ),
    ]
