# Generated by Django 3.2 on 2021-05-21 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newref', '0017_auto_20210521_1015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ref',
            old_name='email_host_cryped_password',
            new_name='crypted_email_host_password',
        ),
    ]
