# Generated by Django 3.2 on 2021-05-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newref', '0018_rename_email_host_cryped_password_ref_crypted_email_host_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ref',
            name='public_key',
        ),
        migrations.AddField(
            model_name='ref',
            name='private_key',
            field=models.FileField(blank=True, null=True, upload_to='private_keys/'),
        ),
    ]
