# Generated by Django 3.2 on 2021-05-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newref', '0019_auto_20210521_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ref',
            name='crypted',
            field=models.BooleanField(default=True),
        ),
    ]
