# Generated by Django 3.2 on 2021-05-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newref', '0022_alter_ref_crypted_email_host_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawvote',
            name='crypted_json',
            field=models.BinaryField(blank=True, max_length=2000, null=True),
        ),
    ]
