# Generated by Django 3.2 on 2021-05-21 19:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('newref', '0023_alter_rawvote_crypted_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='ref',
            name='end_time',
            field=models.TimeField(blank=True, default=datetime.time(16, 0), null=True),
        ),
        migrations.AddField(
            model_name='ref',
            name='start_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 5, 21, 19, 53, 3, 654215, tzinfo=utc), null=True),
        ),
    ]
