# Generated by Django 3.2 on 2021-05-21 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newref', '0024_auto_20210521_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ref',
            name='start_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 5, 21, 22, 4, 23, 408335), null=True),
        ),
    ]
