# Generated by Django 3.2 on 2021-05-26 22:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newref', '0025_alter_ref_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rawvote',
            name='status',
            field=models.CharField(choices=[('INIT', 'Bulletin non envoyé'), ('SENT', 'Bulletin envoyé'), ('STUCK', 'Vote arrêté')], default='INIT', max_length=10),
        ),
        migrations.AlterField(
            model_name='ref',
            name='email_port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ref',
            name='end',
            field=models.DateField(blank=True, default=datetime.date(2021, 6, 3), null=True),
        ),
        migrations.AlterField(
            model_name='ref',
            name='start',
            field=models.DateField(blank=True, default=datetime.date(2021, 5, 27), null=True),
        ),
        migrations.AlterField(
            model_name='ref',
            name='start_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 5, 27, 0, 2, 56, 729195), null=True),
        ),
    ]
