# Generated by Django 3.2 on 2021-06-22 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newref', '0028_auto_20210620_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='ref',
            name='email_failures',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='ref',
            name='end',
            field=models.DateField(blank=True, default=datetime.date(2021, 6, 29), null=True),
        ),
        migrations.AlterField(
            model_name='ref',
            name='start',
            field=models.DateField(blank=True, default=datetime.date(2021, 6, 22), null=True),
        ),
        migrations.AlterField(
            model_name='ref',
            name='start_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 6, 22, 11, 30, 13, 270878), null=True),
        ),
    ]
